[build-system]
requires = ["setuptools>=61.0", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "ease_recommender"
version = "0.1.0"
authors = [{name = "Mateusz Wiktorzak"}]
description = "EASE Recommender with C extensions"
dependencies = [
    "numpy>=2.4.6",
    "scipy>=1.17.1"
]
license = {text = "MIT"}
