name: Deploy Docs
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgsl-dev libomp-dev
      - name: Install other dependencies
        run: |
          pip install sphinx sphinx_rtd_theme .
      - name: Build Docs
        run: |
          sphinx-build docs/source/ build/html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html